FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY protobuf/ ./protobuf/
COPY grpc_server/ ./grpc_server/

RUN sed -i 's/^import monitoring_pb2/from protobuf import monitoring_pb2/' protobuf/monitoring_pb2_grpc.py
RUN python -c "from protobuf import monitoring_pb2, monitoring_pb2_grpc"

ENV GRPC_SERVER_HOST=0.0.0.0

EXPOSE 50051 50052

CMD ["python", "grpc_server/server.py"]
